name: Bug report
description: Report a defect in trader-data.
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Include sample inputs and expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include Python version and relevant runtime details.
    validations:
      required: true
